### ISSUE TITLE
org.jbpm.jbpm3:jbpm-jpdl:3.2.10.SP3_seam2 released into JBoss Releases repository

### ISSUE THREAD

**Issue by mark1900** [mareknovotny/jbpm3-seam#1]
Is this https://github.com/mareknovotny/jbpm3-seam the source that was built to make the "3.2.10.SP3_seam2"release mentioned in [JBSEAM-4900](https://issues.jboss.org/browse/JBSEAM-4900?focusedCommentId=12676856&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-12676856)?

**Background**

I am currently using a custom Seam 2.3 ( [seam_2_3-jee7](https://github.com/andrewscode/jboss-seam/tree/seam_2_3-jee7) ) release in a Wildfly 8.2.0.Final (JEE7) web application.  I am now looking to deploy Seam 2 to Wildfly 10.1.0.Final, though it is looking like I will need to rebuild the following dependency against Hibernate 5.0.10.Final.

```
            <dependency>
                <groupId>org.jbpm.jbpm3</groupId>
                <artifactId>jbpm-jpdl</artifactId>
                <version>3.2.10.SP3_seam2</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.hibernate</groupId>
                        <artifactId>hibernate-core</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
```

In the Seam 2 Task  [JBSEAM-4900](https://issues.jboss.org/browse/JBSEAM-4900?focusedCommentId=12676856&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-12676856) it is mentioned that possibly @mareknovotny released this.

> Marek Novotny added a comment - 14/Mar/12 1:42 PM
> org.jbpm.jbpm3:jbpm-jpdl:3.2.10.SP3_seam2 released into JBoss Releases repository.
> Todo and Dvdstore examples are migrated to EE6 example set to verify the functionality.

I noticed that in the source changelog that [upgraded jbpm3 to be compatible with Hibernate4](https://source.jboss.org/changelog/Seam?cs=14393) it contains the following code change, though I cannot find the original source code ( http://anonsvn.jboss.org/repos/jbpm/jbpm3/ ).

```
- <version>3.2.2</version>
+ <version>3.2.10.SP3_seam2</version>
```

**Comment by mareknovotny** [comment]
yes, this is the fork mentioned in JBSEAM-4900.

Are you sure you would like to go this way? It would be more easier to migrate seam 2 application to CDI.

**Comment by mark1900** [comment]
Great to hear this is the jbpm-jpdl:3.2.10.SP3_seam2 fork, as this does give me the option to migrate this library to Hibernate 5.

In regards to your question about this direction.  Ideally the move to CDI would have been done many years ago, though migrating Seam to Wildfly 8, now Wildfly 10, is currently perceived as less risky and less work for an existing large web application.
